# simple composition based on docs.docker.com/compose/gettingstarted/
services:
  watchlist_tool:
    build: .
    command: python3 -m src.tools.watchlist
    ports:
      - "${WATCHLIST_PORT}:${WATCHLIST_PORT}"
    env_file:
      - .env

  stock_price_tool:
    build: .
    command: python3 -m src.tools.stock_price
    ports:
      - "${STOCK_PRICE_PORT}:${STOCK_PRICE_PORT}"
    env_file:
      - .env

  news_tool:
    build: .
    command: python3 -m src.tools.news
    ports:
      - "${NEWS_PORT}:${NEWS_PORT}"
    env_file:
      - .env

  orchestrator:
    build: .
    command: python3 -m src.main
    depends_on:
      - watchlist_tool
      - stock_price_tool
      - news_tool
    environment:
      - WATCHLIST_HOST=watchlist_tool
      - STOCK_PRICE_HOST=stock_price_tool
      - NEWS_HOST=news_tool
    env_file:
      - .env
